# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.

{ self, inputs, ...}: {
	flake.nixosModules.myMachineHardware = { config, lib, pkgs, modulesPath, ... }: {
		imports =
			[ (modulesPath + "/installer/scan/not-detected.nix")
			];

		boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
		boot.initrd.kernelModules = [ ];
		boot.kernelModules = [ "kvm-amd" ];
		boot.extraModulePackages = [ ];

		fileSystems."/" =
			{ device = "/dev/mapper/luks-ecd8f649-0645-413f-8953-899795c55b08";
				fsType = "ext4";
			};

		boot.initrd.luks.devices."luks-ecd8f649-0645-413f-8953-899795c55b08".device = "/dev/disk/by-uuid/ecd8f649-0645-413f-8953-899795c55b08";

		fileSystems."/boot" =
			{ device = "/dev/disk/by-uuid/A78D-1BE6";
				fsType = "vfat";
				options = [ "fmask=0077" "dmask=0077" ];
			};

		swapDevices =
			[ { device = "/dev/mapper/luks-d5bf71ff-7c9f-4cb1-9659-402952061eca"; }
			];

		nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
		hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
	};
}
