# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ self, inputs, ... }: {
	flake.nixosModules.ssWinningHardware = { config, lib, pkgs, modulesPath, ... }: {
		imports =
			[ (modulesPath + "/installer/scan/not-detected.nix")
			];

		boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
		boot.initrd.kernelModules = [ ];
		boot.kernelModules = [ "kvm-amd" ];
		boot.extraModulePackages = [ ];

		fileSystems."/" =
			{ device = "/dev/mapper/luks-a80365c3-336f-4237-8ee2-d954e1b62d6e";
				fsType = "ext4";
			};

		boot.initrd.luks.devices."luks-a80365c3-336f-4237-8ee2-d954e1b62d6e".device = "/dev/disk/by-uuid/a80365c3-336f-4237-8ee2-d954e1b62d6e";

		fileSystems."/boot" =
			{ device = "/dev/disk/by-uuid/E962-7452";
				fsType = "vfat";
				options = [ "fmask=0077" "dmask=0077" ];
			};

		swapDevices =
			[ { device = "/dev/mapper/luks-0e1995d3-ba0e-40f9-bdaa-c405d243d4f5"; }
			];

		nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
		hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
	};
}
